### ISSUE TITLE
Allow to specify custom schema name

### ISSUE THREAD

**Issue by mgibowski** [Vetspire/endo#15]
## Current behaviour

Currently Endo hard-codes the schema name to "public":
https://github.com/Vetspire/endo/blob/2b7b493e67904ea0f04dd5fa4d39e37afc7495e9/lib/endo/adapters/postgres/table.ex#L56

However, sometimes the application may use a schema with a different name. 

## Connection prefixes in Ecto

Ecto calls those are called "connection prefixes" and there are two ways to set them.

1. By setting a global `connection_prefix`

With the help of the `after_connect` callback as documented in Ecto:

https://hexdocs.pm/ecto_sql/Ecto.Adapters.Postgres.html#module-after-connect-callback

2. By setting a per-query and per-struct prefix

https://hexdocs.pm/ecto/multi-tenancy-with-query-prefixes.html#per-query-and-per-struct-prefixes

Example:

```elixir
MyApp.Repo.all(Sample, prefix: "a_custom_schema_prefix")
```

## Suggestion

It would be great if Endo supported querying schemas other than "public".

One possibility would be allowing to configure a global table schema that would overwrite the default "public" with a config:

```elixir
config :endo, table_schema: "my_custom_schema_other_than_public"
```

Or (and) to mimic the Ecto API, for example:

```elixir
Endo.list_tables(MyApp.Repo, prefix: "my_custom_schema_other_than_public")
```

**Comment by vereis** [comment]
I think both suggestions are reasonable! I'm open to a PR if you want to tackle this, otherwise, I'm sure we can accommodate this relatively soon!

**Comment by vereis** [comment]
Hi @mgibowski I've made a PR which implements both suggestions!

I've written up some documentation and will push it out once tested and merged, but in short, you'll be able to do the following in future:

1) On a query by query basis, mimicking Ecto, you can set `prefix: "my_prefix"` on any `Endo.get_table/3` or `Endo.list_tables/2` calls which works as you'd expect
2) Or, for all queries, we now defer to the config for the default prefix instead of always defaulting to `"public"`. For backwards compatibility we default to `public` if not specified.

Thanks for raising and sorry for the delays ❤️

**Comment by mgibowski** [comment]
Amazing, thanks a lot!
